"use client";
import {useMemo,useState} from "react";
import {Bell,ChevronLeft,ChevronRight,Compass,Globe2,Heart,Home,Image as ImageIcon,Lock,MapPin,MessageCircle,MoreHorizontal,Plus,Search,Settings,ShieldCheck,Sparkles,Users,Video,X,Check,Clock3,CalendarDays,Send,UserPlus,PartyPopper,SlidersHorizontal} from "lucide-react";

const photos=["https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1400&q=85","https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1400&q=85","https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1400&q=85","https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1400&q=85"];
type Screen="discover"|"map"|"create"|"party"|"chat"|"profile"|"memory"|"manage";
const parties=[
{id:"midnight",title:"Midnight at the Manor",area:"Winchester",time:"Tonight · 22:00",people:48,capacity:70,status:"LIVE",privacy:"Public",img:photos[0],host:"Freddie",distance:"2.4 km",tag:"House party"},
{id:"rooftop",title:"Rooftop Season",area:"Southampton",time:"Fri · 21:30",people:31,capacity:45,status:"OPEN",privacy:"Approval",img:photos[1],host:"Maya",distance:"11 km",tag:"Rooftop"},
{id:"warehouse",title:"No Sleep Warehouse",area:"Portsmouth",time:"Sat · 23:00",people:84,capacity:100,status:"OPEN",privacy:"Code",img:photos[2],host:"Leo",distance:"27 km",tag:"Rave"}
];
const waiting=[["Amelia","@amelia.jpg"],["Jack","@jackm"],["Sofia","@sofia"]];

export default function TuCasa(){
const [screen,setScreen]=useState<Screen>("discover"); const [party,setParty]=useState(parties[0]); const [approved,setApproved]=useState(false); const [tab,setTab]=useState("Discover"); const [liked,setLiked]=useState(false); const [dataSaver,setDataSaver]=useState(false); const [requests,setRequests]=useState(waiting);
const nav=(s:Screen,t:string)=>{setScreen(s);setTab(t)};
const hero=useMemo(()=>party,[party]);
return <main className={dataSaver?"app data-saver":"app"}>
<header className="topbar"><button className="brand" onClick={()=>nav("discover","Discover")}><span className="logo">TC</span><span>TuCasa</span></button><div className="top-actions"><button className="icon-btn"><Search size={19}/></button><button className="icon-btn"><Bell size={19}/><i/></button><button className="avatar" onClick={()=>nav("profile","Profile")}>FL</button></div></header>
<div className="shell">
<aside className="sidebar">
<div className="eyebrow">YOUR NIGHT</div>
<Side active={tab==="Discover"} icon={<Compass/>} label="Discover" onClick={()=>nav("discover","Discover")}/>
<Side active={tab==="Map"} icon={<MapPin/>} label="Map" onClick={()=>nav("map","Map")}/>
<Side active={tab==="Chats"} icon={<MessageCircle/>} label="Chats" badge="3" onClick={()=>nav("chat","Chats")}/>
<div className="side-spacer"/>
<Side active={tab==="Profile"} icon={<Users/>} label="Profile" onClick={()=>nav("profile","Profile")}/>
<button className="settings-row" onClick={()=>setDataSaver(v=>!v)}><Settings size={18}/><span>Data saver</span><span className={"toggle "+(dataSaver?"on":"")}><b/></span></button>
</aside>
<section className="content">
{screen==="discover"&&<Discover onOpen={(p:any)=>{setParty(p);nav("party","Discover")}} liked={liked} setLiked={setLiked}/>}
{screen==="map"&&<MapView onOpen={(p:any)=>{setParty(p);nav("party","Map")}}/>}
{screen==="create"&&<Create onDone={(p:any)=>{setParty(p);nav("party","Discover")}}/>}
{screen==="party"&&<Party party={hero} approved={approved} onJoin={()=>setApproved(true)} onManage={()=>nav("manage","Discover")} onMemory={()=>nav("memory","Discover")} onChat={()=>nav("chat","Chats")} />}
{screen==="manage"&&<Manage requests={requests} setRequests={setRequests} onBack={()=>nav("party","Discover")}/>}
{screen==="chat"&&<Chat onCreate={()=>nav("create","Chats")} onParty={()=>nav("party","Chats")}/>}
{screen==="profile"&&<Profile onParty={()=>nav("memory","Profile")}/>}
{screen==="memory"&&<Memory party={hero} onBack={()=>nav("discover","Discover")}/>}
</section>
</div>
<nav className="mobile-nav"><NavItem icon={<Compass/>} label="Discover" active={tab==="Discover"} onClick={()=>nav("discover","Discover")}/><NavItem icon={<MapPin/>} label="Map" active={tab==="Map"} onClick={()=>nav("map","Map")}/><button className="create-fab" onClick={()=>nav("create","Create")}><Plus/></button><NavItem icon={<MessageCircle/>} label="Chats" active={tab==="Chats"} onClick={()=>nav("chat","Chats")}/><NavItem icon={<Users/>} label="You" active={tab==="Profile"} onClick={()=>nav("profile","Profile")}/></nav>
</main>}

function Side({icon,label,active,badge,onClick}:any){return <button className={"side-row "+(active?"active":"")} onClick={onClick}>{icon}<span>{label}</span>{badge&&<em>{badge}</em>}</button>}
function NavItem({icon,label,active,onClick}:any){return <button className={"nav-item "+(active?"active":"")} onClick={onClick}>{icon}<small>{label}</small></button>}

function Discover({onOpen,liked,setLiked}:any){return <div className="page"><div className="page-head"><div><span className="eyebrow">THURSDAY · 18:42</span><h1>What's happening?</h1><p>Find your people. Find your night.</p></div><button className="pill"><SlidersHorizontal size={16}/> Filters</button></div><div className="chips"><span className="chip active">Near you</span><span className="chip">Tonight</span><span className="chip">This weekend</span><span className="chip">Friends</span></div><section className="hero-grid"><div className="hero-card" style={{backgroundImage:"url("+photos[0]+")"}} onClick={()=>onOpen(parties[0])}><div className="hero-shade"/><div className="live-pill"><i/> LIVE NOW</div><button className="heart" onClick={e=>{e.stopPropagation();setLiked(!liked)}}>{liked?<Heart fill="currentColor"/>:<Heart/>}</button><div className="hero-copy"><span className="micro">HOUSE PARTY · 48 / 70</span><h2>Midnight at<br/>the Manor</h2><div className="meta"><span><MapPin/> Winchester</span><span><Clock3/> 22:00</span></div><div className="people"><div className="faces"><span>AM</span><span>JK</span><span>SO</span><span>+45</span></div><span>48 people are going</span></div></div></div><div className="side-cards"><PartyMini p={parties[1]} onOpen={onOpen}/><PartyMini p={parties[2]} onOpen={onOpen}/></div></section><div className="section-title"><div><span className="eyebrow">FOR YOU</span><h3>More happening nearby</h3></div><button className="text-btn">See all <ChevronRight/></button></div><div className="party-list">{parties.map(p=><PartyRow key={p.id} p={p} onOpen={onOpen}/>)}</div></div>}

function PartyMini({p,onOpen}:any){return <article className="mini-card" style={{backgroundImage:"url("+p.img+")"}} onClick={()=>onOpen(p)}><div className="card-shade"/><div className="mini-top"><span>{p.status}</span><span>{p.privacy}</span></div><div className="mini-copy"><h3>{p.title}</h3><p>{p.area} · {p.time}</p><strong>{p.people} / {p.capacity} going</strong></div></article>}
function PartyRow({p,onOpen}:any){return <article className="party-row" onClick={()=>onOpen(p)}><div className="row-img" style={{backgroundImage:"url("+p.img+")"}}/><div className="row-main"><span className="eyebrow">{p.tag.toUpperCase()}</span><h3>{p.title}</h3><p><MapPin/> {p.area} · {p.time}</p></div><div className="row-stat"><b>{p.people}</b><small>going</small></div><ChevronRight/></article>}

function MapView({onOpen}:any){return <div className="page map-page"><div className="page-head"><div><span className="eyebrow">LIVE MAP</span><h1>Find the night.</h1><p>Parties around you, right now.</p></div><button className="pill"><Globe2 size={16}/> Winchester</button></div><div className="map"><div className="map-grid"/>{parties.map((p,i)=><button key={p.id} className={"pin pin"+i} onClick={()=>onOpen(p)}><span>{p.people}</span><i/></button>)}<div className="map-label l1">MIDNIGHT</div><div className="map-label l2">ROOFTOP</div><div className="map-label l3">WAREHOUSE</div></div></div>}

function Party({party,approved,onJoin,onManage,onMemory,onChat}:any){const [menu,setMenu]=useState(false); const isLive=party.status==="LIVE";return <div className="page"><button className="back-btn"><ChevronLeft/> Discover</button><div className="party-layout"><div className="party-visual" style={{backgroundImage:"url("+party.img+")"}}><div className="hero-shade"/><div className="visual-top"><span className="status-pill"><i/> {party.status}</span><button className="icon-btn glass"><MoreHorizontal onClick={()=>setMenu(!menu)}/></button></div><div className="visual-bottom"><span className="eyebrow">{party.tag.toUpperCase()}</span><h1>{party.title}</h1><p><MapPin/> {party.area} · {party.time}</p></div></div><div className="party-panel"><div className="host-line"><span className="host-avatar">FL</span><div><small>HOSTED BY</small><b>{party.host}</b></div><button className="follow-btn">Follow</button></div><div className="stat-grid"><div><b>{party.people}</b><span>going</span></div><div><b>{party.capacity-party.people}</b><span>spots left</span></div><div><b>{party.privacy}</b><span>access</span></div></div>{approved?<div className="approved"><div className="check-circle"><Check/></div><div><b>You're in.</b><p>Address unlocked. The party chat is ready.</p></div></div>:<div className="join-box"><div className="lock-row"><ShieldCheck/><div><b>{party.privacy==="Approval"?"Host approval required":"You're invited to join"}</b><p>{party.privacy==="Approval"?"Request access and wait for the host.":"Join instantly and get the details."}</p></div></div><button className="primary-btn" onClick={onJoin}>{party.privacy==="Approval"?"REQUEST TO JOIN":"JOIN PARTY"} <ChevronRight/></button></div>}<div className="details"><div><CalendarDays/><span><b>{party.time}</b><small>Schedule</small></span></div><div><MapPin/><span><b>{approved?"Exact address revealed":"Location hidden until you're in"}</b><small>Location</small></span></div><div><Users/><span><b>{party.capacity} maximum</b><small>Capacity</small></span></div></div><div className="party-actions"><button onClick={onChat}><MessageCircle/> Party chat</button>{isLive&&<button onClick={onMemory}><ImageIcon/> Memories</button>}<button onClick={onManage}><Settings/> Manage</button></div></div></div></div>}

function Manage({requests,setRequests,onBack}:any){return <div className="page"><button className="back-btn" onClick={onBack}><ChevronLeft/> Party</button><div className="manage-head"><div><span className="eyebrow">HOST CONTROL</span><h1>Midnight at the Manor</h1><p>Everything important, in one place.</p></div><button className="danger">Cancel party</button></div><div className="control-grid"><section className="control-card"><div className="control-head"><div><span className="eyebrow">WAITING ROOM</span><h2>{requests.length} requests</h2></div><button className="primary-small" onClick={()=>setRequests([])}><Check/> Accept all</button></div>{requests.length?requests.map((r:any)=><div className="request" key={r[0]}><div className="request-avatar">{r[0].slice(0,2)}</div><div><b>{r[0]}</b><small>{r[1]}</small></div><div className="request-actions"><button onClick={()=>setRequests(requests.filter((x:any)=>x[0]!==r[0]))}><Check/></button><button className="reject"><X/></button></div></div>):<div className="empty"><Check/> Waiting room is clear.</div>}</section><section className="control-card"><span className="eyebrow">PARTY SETTINGS</span><h2>Rules & access</h2><Setting label="Require approval" value/><Setting label="Branches after party" value={false}/><Setting label="Recurring party" value/><Setting label="Reveal address on approval" value/></section></div></div>}
function Setting({label,value}:any){const [on,setOn]=useState(value);return <button className="setting" onClick={()=>setOn(!on)}><span>{label}</span><span className={"toggle "+(on?"on":"")}><b/></span></button>}

function Chat({onCreate,onParty}:any){const [messages,setMessages]=useState(["Anyone up for Friday?","I can host. Let’s make it a proper one.","Say less 🔥"]);const [draft,setDraft]=useState("");return <div className="page chat-page"><div className="chat-head"><div><span className="eyebrow">GROUP CHAT · 7 PEOPLE</span><h1>Friday plans</h1></div><button className="primary-small" onClick={onCreate}><Plus/> Create party</button></div><div className="chat-window">{messages.map((m,i)=><div className={"bubble "+(i===2?"me":"")} key={i}>{m}<small>{i===2?"You":"Maya"} · {i+1}8:4{i}</small></div>)}</div><div className="chat-composer"><button><Plus/></button><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&draft.trim()){setMessages([...messages,draft]);setDraft("")}}} placeholder="Message the group…"/><button className="send" onClick={()=>{if(draft.trim()){setMessages([...messages,draft]);setDraft("")}}}><Send/></button></div><button className="linked-party" onClick={onParty}><div className="tiny-img" style={{backgroundImage:"url("+photos[0]+")"}}/><div><span>PLANNING PARTY</span><b>Midnight at the Manor</b></div><ChevronRight/></button></div>}

function Create({onDone}:any){const [title,setTitle]=useState("");const [approval,setApproval]=useState(true);const [branch,setBranch]=useState(false);const [recurring,setRecurring]=useState(false);return <div className="page create-page"><div className="page-head"><div><span className="eyebrow">NEW PARTY</span><h1>Make something happen.</h1><p>Start with a name. Fill the rest when you know.</p></div><span className="draft-pill">DRAFT SAVES AUTOMATICALLY</span></div><div className="create-grid"><section className="create-form"><label>Party name<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Midnight at mine"/></label><label>When<input type="datetime-local"/></label><label>Where<input placeholder="Add a location later"/></label><div className="two"><label>Capacity<input type="number" placeholder="70"/></label><label>Privacy<select><option>Public</option><option>Friends</option><option>Invite only</option><option>Join code</option></select></label></div><label>Description<textarea placeholder="What's the vibe?"/></label><div className="switch-list"><Setting label="Require host approval" value={approval}/><Setting label="Allow branches" value={branch}/><Setting label="Repeat this party" value={recurring}/></div><button className="primary-btn" disabled={!title.trim()} onClick={()=>onDone({id:"new",title,area:"Winchester",time:"This weekend",people:1,capacity:70,status:"OPEN",privacy:approval?"Approval":"Public",img:photos[0],host:"You",distance:"—",tag:"House party"})}>Create party <PartyPopper/></button></section><section className="create-preview"><div className="preview-card" style={{backgroundImage:"url("+photos[1]+")"}}><div className="hero-shade"/><div className="preview-copy"><span className="micro">YOUR PARTY</span><h2>{title||"Your party name"}</h2><p>Details can come later.</p></div></div><div className="preview-note"><Sparkles/><div><b>Built for real nights.</b><p>Location, approval, capacity, branches and recurrence can all evolve after creation.</p></div></div></section></div></div>}

function Profile({onParty}:any){return <div className="page"><div className="profile-hero"><div className="profile-avatar">FL</div><div><span className="eyebrow">@freddie</span><h1>Freddie Ley</h1><p>Host, connector, occasional chaos agent.</p></div><button className="pill"><Settings/> Edit profile</button></div><div className="profile-stats"><div><b>284</b><span>Followers</span></div><div><b>391</b><span>Following</span></div><div><b>68</b><span>Friends</span></div></div><div className="section-title"><div><span className="eyebrow">YOUR NIGHTS</span><h3>Memories</h3></div></div><div className="memory-grid">{photos.map((p,i)=><button key={p} className="memory-tile" style={{backgroundImage:"url("+p+")"}} onClick={onParty}><span>{[47,23,81,36][i]} memories</span></button>)}</div></div>}

function Memory({party,onBack}:any){return <div className="page"><button className="back-btn" onClick={onBack}><ChevronLeft/> Back</button><div className="memory-head"><div><span className="eyebrow">MEMORY DUMP</span><h1>{party.title}</h1><p>47 memories · 23 people · 14 hours ago</p></div><button className="primary-small"><Plus/> Add photos</button></div><div className="masonry">{[...photos,...photos].map((p,i)=><div className={"memory-photo h"+(i%3)} key={i} style={{backgroundImage:"url("+p+")"}}><span>{["You","Maya","Jack","Sofia"][i%4]}</span></div>)}</div></div>}
